// Code generated by BarefootJS. DO NOT EDIT.
package views

import (
	"math/rand"

	bf "github.com/barefootjs/runtime/bf"
)

// randomID generates a random string of length n for ScopeID.
func randomID(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

// ControlsInput is the user-facing input type.
type ControlsInput struct {
	ScopeID  string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount  string // Optional: slot id in parent
	Text     interface{}
	DeviceID string
}

// ControlsProps is the props type for the Controls component.
type ControlsProps struct {
	ScopeID       string                 `json:"-"`
	BfIsRoot      bool                   `json:"-"`
	BfIsChild     bool                   `json:"-"`
	BfParent      string                 `json:"-"`
	BfMount       string                 `json:"-"`
	BfDataKey     string                 `json:"-"`
	Scripts       *bf.ScriptCollector    `json:"-"`
	BfCallerProps map[string]interface{} `json:"-"`
	Text          interface{}            `json:"text"`
	DeviceID      string                 `json:"deviceID"`
	Busy          bool                   `json:"-"`
	Message       interface{}            `json:"-"`
	Failed        bool                   `json:"-"`
	ImageURL      string                 `json:"-"`
	Captured      string                 `json:"-"`
	ScreenOn      bool                   `json:"-"`
	Brightness    int                    `json:"-"`
	Volume        int                    `json:"-"`
	CurrentURL    string                 `json:"-"`
}

// PageCardsItem is a synthesised type for an anonymous object type (#2674).
type PageCardsItem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// PageInput is the user-facing input type.
type PageInput struct {
	ScopeID  string // Optional: if empty, random ID is generated
	BfParent string // Optional: parent scope id
	BfMount  string // Optional: slot id in parent
	Text     interface{}
	Title    string
	DetailID string
	Cards    []PageCardsItem
}

// PageProps is the props type for the Page component.
type PageProps struct {
	ScopeID        string                 `json:"-"`
	BfIsRoot       bool                   `json:"-"`
	BfIsChild      bool                   `json:"-"`
	BfParent       string                 `json:"-"`
	BfMount        string                 `json:"-"`
	BfDataKey      string                 `json:"-"`
	Scripts        *bf.ScriptCollector    `json:"-"`
	BfCallerProps  map[string]interface{} `json:"-"`
	Text           interface{}            `json:"text"`
	Title          string                 `json:"title"`
	DetailID       string                 `json:"detailID"`
	Cards          []PageCardsItem        `json:"cards"`
	ControlsSlot23 ControlsProps          `json:"-"`
}

// StatusRowsItem is a synthesised type for an anonymous object type (#2674).
type StatusRowsItem struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// StatusInput is the user-facing input type.
type StatusInput struct {
	ScopeID     string // Optional: if empty, random ID is generated
	BfParent    string // Optional: parent scope id
	BfMount     string // Optional: slot id in parent
	Text        interface{}
	State       string
	StateClass  string
	Error       string
	Stale       bool
	LastSuccess string
	LastAttempt string
	Rows        []StatusRowsItem
}

// StatusProps is the props type for the Status component.
type StatusProps struct {
	ScopeID       string                 `json:"-"`
	BfIsRoot      bool                   `json:"-"`
	BfIsChild     bool                   `json:"-"`
	BfParent      string                 `json:"-"`
	BfMount       string                 `json:"-"`
	BfDataKey     string                 `json:"-"`
	Scripts       *bf.ScriptCollector    `json:"-"`
	BfCallerProps map[string]interface{} `json:"-"`
	Text          interface{}            `json:"text"`
	State         string                 `json:"state"`
	StateClass    string                 `json:"stateClass"`
	Error         string                 `json:"error"`
	Stale         bool                   `json:"stale"`
	LastSuccess   string                 `json:"lastSuccess"`
	LastAttempt   string                 `json:"lastAttempt"`
	Rows          []StatusRowsItem       `json:"rows"`
}

// NewControlsProps creates ControlsProps from ControlsInput.
func NewControlsProps(in ControlsInput) ControlsProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Controls_" + randomID(6)
	}

	bfCallerProps := map[string]interface{}{}
	bfCallerProps["text"] = in.Text
	bfCallerProps["deviceID"] = in.DeviceID

	return ControlsProps{
		ScopeID:       scopeID,
		BfParent:      in.BfParent,
		BfMount:       in.BfMount,
		BfCallerProps: bfCallerProps,
		Text:          in.Text,
		DeviceID:      in.DeviceID,
		Busy:          false,
		Message:       nil,
		Failed:        false,
		ImageURL:      "",
		Captured:      "",
		ScreenOn:      false,
		Brightness:    50,
		Volume:        20,
		CurrentURL:    "",
	}
}

// NewPageProps creates PageProps from PageInput.
func NewPageProps(in PageInput) PageProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Page_" + randomID(6)
	}

	bfCallerProps := map[string]interface{}{}
	bfCallerProps["text"] = in.Text
	bfCallerProps["title"] = in.Title
	bfCallerProps["detailID"] = in.DetailID
	bfCallerProps["cards"] = in.Cards

	return PageProps{
		ScopeID:       scopeID,
		BfParent:      in.BfParent,
		BfMount:       in.BfMount,
		BfCallerProps: bfCallerProps,
		Text:          in.Text,
		Title:         in.Title,
		DetailID:      in.DetailID,
		Cards:         in.Cards,
		ControlsSlot23: NewControlsProps(ControlsInput{
			ScopeID:  scopeID + "_s23",
			BfParent: scopeID,
			BfMount:  "s23",
			DeviceID: in.DetailID,
			Text:     in.Text,
		}),
	}
}

// NewStatusProps creates StatusProps from StatusInput.
func NewStatusProps(in StatusInput) StatusProps {
	scopeID := in.ScopeID
	if scopeID == "" {
		scopeID = "Status_" + randomID(6)
	}

	bfCallerProps := map[string]interface{}{}
	bfCallerProps["text"] = in.Text
	bfCallerProps["state"] = in.State
	bfCallerProps["stateClass"] = in.StateClass
	bfCallerProps["error"] = in.Error
	bfCallerProps["stale"] = in.Stale
	bfCallerProps["lastSuccess"] = in.LastSuccess
	bfCallerProps["lastAttempt"] = in.LastAttempt
	bfCallerProps["rows"] = in.Rows

	return StatusProps{
		ScopeID:       scopeID,
		BfParent:      in.BfParent,
		BfMount:       in.BfMount,
		BfCallerProps: bfCallerProps,
		Text:          in.Text,
		State:         in.State,
		StateClass:    in.StateClass,
		Error:         in.Error,
		Stale:         in.Stale,
		LastSuccess:   in.LastSuccess,
		LastAttempt:   in.LastAttempt,
		Rows:          in.Rows,
	}
}
